version: "3"
services: 
  node:
    build: .
    ports: 
      - 3000:3000
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules/bcrypt
    depends_on: 
      - mongo
  mongo:
    image: mongo
    container_name: global-mongo-services
    restart: unless-stopped
    volumes: 
      - mongo_data:/data/configdb
      - mongo_data:/data/db
    ports: 
      - 27017:27017
volumes:
  mongo_data: {}